import Image from 'next/image'
import { Oswald } from 'next/font/google'
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import me from "../public/img/mee.png"

const oswald = Oswald({ 
  subsets: ['latin'],
  weight: ['700']
 })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luca Raveri | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white">
        <section className="min-h-screen bg-gradient-to-r from-gray-200 via-white to-gray-200">
          <nav className='p-7 mb-12 flex justify-between bg-gradient-to-r from-blue-200 via-blue-300 to-green-300 lg:p-8'>
            <div className={oswald.className}>
            <h1 className="text-gray-500 font-bold text-2xl">Luca Raveri</h1>
            </div>
            <ul className="flex items-center">
              <li>
                <a
                  className="bg-cyan-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center lg:p-8">
            <div className="mx-auto mt-5 bg-gradient-to-b from-blue-300 rounded-full w-60 h-60 relative overflow-hidden">
              <Image src={me} layout="fill" objectFit="cover" />
            </div>
            <div className={oswald.className}>
            <h2 className="text-4xl py-2 text-cyan-500 font-medium">
              Luca Raveri
            </h2>
            </div>
            <h3 className="text-xl text-gray-500 py-2">
              Developer and designer.
            </h3>
            <p className="text-md mb-8 px-5 leading-8 text-gray-700">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
          </div>
          <footer>
            <div className="p-5 text-3xl flex justify-center gap-16 text-gray-500">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
          </footer>
        </section>
      </main>
    </div>
  )
}
